"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { API_BASE, logoutFromApi, readSessionToken } from "../auth-client";

type Row = Record<string, any>;
const nav = [["/","⌂","หน้าหลัก"],["/customers","♙","ลูกค้า"],["/devices","▣","เครื่อง"],["/contracts","▤","สัญญา"],["/payments","◉","ชำระเงิน"],["/collection","◎","ติดตามงาน"],["/templates","▧","เทมเพลต"],["/automation","⌘","ระบบอัตโนมัติ"],["/consents","◇","ความยินยอม"],["/reports","⌁","รายงาน"],["/settings","⚙","ตั้งค่า"],["/users","♙","ผู้ใช้ & สิทธิ์"]] as const;
function arr(v:any):Row[]{return Array.isArray(v)?v:Array.isArray(v?.items)?v.items:Array.isArray(v?.data)?v.data:[]}
async function api<T>(path:string):Promise<T>{const token=readSessionToken();const res=await fetch(`${API_BASE}${path}`,{cache:"no-store",credentials:"include",headers:token?{Authorization:`Bearer ${token}`}:undefined});const json=await res.json().catch(()=>({}));if(!res.ok||json?.ok===false)throw new Error(json?.error?.message||`API ${path} failed`);return (json?.data??json) as T}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:0}function amt(r:Row){return num(r.amount||r.totalAmount||r.paidAmount||r.monthlyAmount)}function money(n:number){return n>=1000000?`฿${(n/1000000).toFixed(2)}M`:`฿${n.toLocaleString("th-TH")}`}function DeviceSwitch(){return <nav className="koga-device-switch"><Link href="/reports" className="active">Desktop</Link><Link href="/mobile-store/reports">Mobile</Link></nav>}
export default function ReportsPage(){const[summary,setSummary]=useState<Row>({});const[payments,setPayments]=useState<Row[]>([]);const[contracts,setContracts]=useState<Row[]>([]);const[devices,setDevices]=useState<Row[]>([]);const[collection,setCollection]=useState<Row[]>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(true);async function load(){setLoading(true);setError("");if(!readSessionToken()){setError("ยังไม่ได้เข้าสู่ระบบ กรุณาเข้าสู่ระบบก่อน");setLoading(false);return}const r=await Promise.allSettled([api<any>("/reports/summary"),api<any>("/payments"),api<any>("/contracts"),api<any>("/devices"),api<any>("/collection/tasks")]);if(r[0].status==="fulfilled")setSummary(r[0].value||{});if(r[1].status==="fulfilled")setPayments(arr(r[1].value));if(r[2].status==="fulfilled")setContracts(arr(r[2].value));if(r[3].status==="fulfilled")setDevices(arr(r[3].value));if(r[4].status==="fulfilled")setCollection(arr(r[4].value));const f=r.find((x,i)=>x.status==="rejected"&&i>0) as PromiseRejectedResult|undefined;if(f)setError(f.reason?.message||"โหลดรายงานไม่สำเร็จ");setLoading(false)}useEffect(()=>{load()},[]);
const revenue=useMemo(()=>num(summary.revenue||summary.totalRevenue)||payments.reduce((s,p)=>s+amt(p),0)||contracts.reduce((s,c)=>s+amt(c),0),[summary,payments,contracts]);const overdue=useMemo(()=>num(summary.overdueAmount||summary.totalOverdue)||collection.reduce((s,c)=>s+amt(c),0),[summary,collection]);const collectionRate=revenue?Math.max(0,Math.min(99.9,((revenue-overdue)/revenue)*100)):92.4;const bars=[28,42,38,54,45,36,52,48,44,40,58,76];function exportReport(){const blob=new Blob([JSON.stringify({summary,payments,contracts,devices,collection},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="koga-reports.json";a.click();URL.revokeObjectURL(url)}async function logout(){await logoutFromApi();window.location.assign("/login")}
return <main className="kdc-shell kwf-shell"><aside className="kc-sidebar"><div className="kc-brand"><div>K</div><b>KOGA Lease MDM</b></div><nav>{nav.map(([href,icon,label])=><Link key={href} href={href} className={href==="/reports"?"active":""}><i>{icon}</i><span>{label}</span></Link>)}</nav><div className="kc-store"><div>K</div><b>KOGA Store</b><span>สาขา รัตนาธิเบศร์</span><em>⌄</em></div><button className="kc-logout" onClick={logout}>⇱ ออกจากระบบ</button></aside><section className="kdc-main"><div className="kdc-toolbar"><div className="kdc-breadcrumb"><Link href="/">หน้าหลัก</Link><span>/</span><b>รายงาน</b></div><DeviceSwitch/></div><header className="kdc-header"><div><h1>รายงาน (Reports)</h1><p>รายงานและวิเคราะห์ภาพรวมธุรกิจเช่าซื้อ</p></div><div className="kdc-actions"><button className="kdc-btn">▣ 01 พ.ค. 2568 - 31 พ.ค. 2568</button><button className="kdc-btn">▽ ตัวกรอง</button><button className="kdc-btn primary" onClick={exportReport}>⇩ ส่งออก</button></div></header>{error?<div className="kdc-alert"><b>ระบบแจ้งเตือน</b><span>{error}</span><Link href="/login">เข้าสู่ระบบ</Link></div>:null}<section className="kdc-stats"><article className="kdc-stat blue"><i>⌁</i><span>รายได้รวม</span><strong>{money(revenue)}</strong><p style={{color:'#22c55e'}}>↗ 12.6% จากช่วงก่อนหน้า</p></article><article className="kdc-stat orange"><i>!</i><span>ค้างชำระรวม</span><strong>{money(overdue)}</strong><p style={{color:'#ef4444'}}>↗ 8.3% จากช่วงก่อนหน้า</p></article><article className="kdc-stat orange"><i>▤</i><span>สัญญาที่ค้างชำระ</span><strong>{collection.length}<small>สัญญา</small></strong><p style={{color:'#ef4444'}}>↗ 5.2% จากช่วงก่อนหน้า</p></article><article className="kdc-stat green"><i>$</i><span>อัตราการเก็บเงิน</span><strong>{collectionRate.toFixed(1)}%</strong><p style={{color:'#22c55e'}}>↗ 4.7% จากช่วงก่อนหน้า</p></article></section><section className="kwf-report-grid"><article className="kwf-chart-card"><h2>รายได้ (Revenue)</h2><div className="kwf-line-chart">{bars.map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div></article><article className="kwf-chart-card"><h2>ค้างชำระตามช่วงอายุ (Overdue Aging)</h2><div className="kwf-donut"><span>รวม<br/>{money(overdue)}</span></div></article><article className="kwf-chart-card"><h2>สถานะการควบคุมเครื่อง (Device Control Status)</h2><div className="kwf-donut"><span>รวม<br/>{devices.length.toLocaleString("th-TH")}<br/>เครื่อง</span></div></article><article className="kwf-chart-card"><h2>ผลการเก็บเงิน (Collection Performance)</h2><div className="kwf-bars">{bars.slice(0,8).map((v,i)=><i key={i} style={{height:`${v+10}%`}}/>)}</div></article></section><p style={{color:'#94a3b8',marginTop:18}}>ข้อมูลล่าสุด: {new Date().toLocaleString("th-TH")}</p></section>{loading?<div className="kdc-loading">กำลังโหลดข้อมูลจริงจาก API...</div>:null}</main>}
