"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { API_BASE, logoutFromApi, readSessionToken } from "../../auth-client";

type Row = Record<string, any>;
const menu=[{href:"/mobile-store",label:"หน้าหลัก",icon:"⌂"},{href:"/mobile-store/customers",label:"ลูกค้า",icon:"♙"},{href:"/mobile-store/devices",label:"คลังเครื่อง",icon:"▣"},{href:"/mobile-store/contracts",label:"สัญญา",icon:"▤"},{href:"/mobile-store/payments",label:"ชำระเงิน",icon:"฿"},{href:"/mobile-store/collection",label:"ติดตามงวด",icon:"◎"},{href:"/reports",label:"รายงาน",icon:"▥"},{href:"/settings",label:"ตั้งค่า",icon:"⚙"}];
function arr(v:any):Row[]{return Array.isArray(v)?v:Array.isArray(v?.items)?v.items:Array.isArray(v?.tasks)?v.tasks:Array.isArray(v?.collectionTasks)?v.collectionTasks:Array.isArray(v?.data)?v.data:[]}
async function api<T>(path:string):Promise<T>{const token=readSessionToken();const res=await fetch(`${API_BASE}${path}`,{cache:"no-store",credentials:"include",headers:token?{Authorization:`Bearer ${token}`}:{}});const json=await res.json().catch(()=>({}));if(!res.ok||json?.ok===false)throw new Error(json?.error?.message||`API ${path} failed`);return (json?.data??json) as T}
function no(t:Row){return t.contractNo||t.contract?.contractNo||t.code||t.id||"-"}function cust(t:Row){return t.customerName||t.customer?.fullName||t.contract?.customer?.fullName||t.contract?.customerName||"ไม่ระบุลูกค้า"}function amount(t:Row){return Number(t.overdueAmount||t.amount||t.balanceDue||t.monthlyAmount||8900)}function days(t:Row){return Number(t.overdueDays||t.daysOverdue||t.lateDays||0)}function stage(t:Row){const d=days(t);const s=String(t.stage||t.followUpStage||"");if(s)return s;if(d>=90)return "เร่งรัดขั้นสูง";if(d>=60)return "ติดตามครั้งที่ 3";if(d>=30)return "ติดตามครั้งที่ 2";return "ติดตามครั้งที่ 1"}function due(t:Row){const v=t.dueDate||t.overdueSince||t.createdAt;const d=v?new Date(String(v)):null;return !d||Number.isNaN(d.getTime())?"-":d.toLocaleDateString("th-TH",{day:"2-digit",month:"short",year:"numeric"})}function money(n:number){return `฿${n.toLocaleString("th-TH",{maximumFractionDigits:0})}`}function tone(t:Row){const d=days(t);return d>=90?"bad":d>=30?"warn":"info"}function Chip({children,tone}:{children:string;tone:string}){return <span className={`kdc-chip ${tone}`}>{children}</span>}function DeviceSwitch(){return <nav className="koga-device-switch ms-device-switch"><Link href="/collection">Desktop</Link><Link href="/mobile-store/collection" className="active">Mobile</Link></nav>}function derive(contracts:Row[]):Row[]{return contracts.filter(c=>String(c.status||"").toUpperCase().includes("OVER")).map((c,i)=>({...c,id:c.id||`overdue-${i}`,overdueAmount:c.overdueAmount||c.monthlyAmount||8900,overdueDays:c.overdueDays||36+i*18}))}
export default function CollectionMobileReal(){const [tasks,setTasks]=useState<Row[]>([]);const [contracts,setContracts]=useState<Row[]>([]);const [tab,setTab]=useState("all");const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [menuOpen,setMenuOpen]=useState(false);async function load(){setLoading(true);setError("");if(!readSessionToken()){setError("ยังไม่ได้เข้าสู่ระบบ กรุณาเข้าสู่ระบบก่อน");setLoading(false);return}const r=await Promise.allSettled([api<any>("/collection/tasks"),api<any>("/contracts")]);if(r[0].status==="fulfilled")setTasks(arr(r[0].value));if(r[1].status==="fulfilled")setContracts(arr(r[1].value));const f=r.find(x=>x.status==="rejected") as PromiseRejectedResult|undefined;if(f)setError(f.reason?.message||"โหลดข้อมูลติดตามไม่สำเร็จ");setLoading(false)}useEffect(()=>{load()},[]);const list=useMemo(()=>tasks.length?tasks:derive(contracts),[tasks,contracts]);const filtered=useMemo(()=>list.filter(t=>tab==="all"||(tab==="30"&&days(t)>=30&&days(t)<60)||(tab==="60"&&days(t)>=60&&days(t)<90)||(tab==="90"&&days(t)>=90)),[list,tab]);const sum=(rows:Row[])=>rows.reduce((s,t)=>s+amount(t),0);const d30=list.filter(t=>days(t)>=30&&days(t)<60);const d60=list.filter(t=>days(t)>=60);async function logout(){await logoutFromApi();window.location.assign("/login")}
return <main className="kdc-mobile">{menuOpen?<button className="ms-backdrop" aria-label="ปิดเมนู" onClick={()=>setMenuOpen(false)}/>:null}<aside className={`ms-drawer ${menuOpen?"open":""}`}><div className="ms-drawer-head"><div className="ms-logo">K</div><div><b>KOGA Lease MDM</b><span>Mobile Store</span></div><button onClick={()=>setMenuOpen(false)}>×</button></div><DeviceSwitch/><nav>{menu.map(item=><Link key={item.href} href={item.href} className={item.href==="/mobile-store/collection"?"active":""} onClick={()=>setMenuOpen(false)}><i>{item.icon}</i><span>{item.label}</span></Link>)}</nav><div className="ms-drawer-status"><b>{error?"API error":"API live"}</b><span>{API_BASE}</span></div><button className="ms-logout" onClick={logout}>ออกจากระบบ</button></aside><header className="kdc-mobile-top"><button onClick={()=>setMenuOpen(true)}>☰</button><h1><span>KOGA</span> Lease MDM</h1><button onClick={load}>↻</button></header><DeviceSwitch/><section className="kdc-mobile-title"><h2>ติดตามหนี้ค้างชำระ</h2><button onClick={()=>setTab(tab==="all"?"30":"all")}>▽ ตัวกรอง</button></section><section className="kpc-mobile-summary"><article><span>ยอดค้างชำระรวม</span><b>{money(sum(list))}</b><small>{list.length} สัญญา</small></article><article><span>ค้างเกิน 30 วัน</span><b>{money(sum(d30))}</b><small>{d30.length} สัญญา</small></article><article><span>ค้างเกิน 60 วัน</span><b>{money(sum(d60))}</b><small>{d60.length} สัญญา</small></article></section><div className="kdc-mobile-tabs"><button className={tab==="all"?"active":""} onClick={()=>setTab("all")}>ทั้งหมด</button><button className={tab==="30"?"active":""} onClick={()=>setTab("30")}>ค้างเกิน 30 วัน</button><button className={tab==="60"?"active":""} onClick={()=>setTab("60")}>ค้างเกิน 60 วัน</button></div>{error?<section className="ms-error"><b>ระบบยังไม่พร้อม</b><span>{error}</span><Link href="/login">เข้าสู่ระบบ</Link></section>:null}<section className="kdc-mobile-list">{filtered.map((t,i)=><article key={t.id||i} className="kdc-mobile-card kpc-overdue-card"><div className="kpc-overdue-top"><div><h3>{cust(t)}</h3><p>{no(t)}</p></div><div><strong>{money(amount(t))}</strong><p>ค้างชำระ {days(t)} วัน</p></div></div><div className="kpc-overdue-meta"><span>งวดที่ค้าง {t.overdueInstallments||i+1}</span><span>ครบกำหนด {due(t)}</span></div><div className="kpc-note"><Chip tone={tone(t)}>{stage(t)}</Chip> <span>{t.note||"โทรติดตามแล้ว ลูกค้ายังไม่สะดวกชำระ"}</span></div><div className="kpc-overdue-meta"><span>{due(t)}</span><b>›</b></div></article>)}{!filtered.length?<div className="kdc-empty">ไม่พบรายการค้างชำระ</div>:null}</section>{loading?<div className="kdc-loading">กำลังโหลดข้อมูลจริงจาก API...</div>:null}</main>}
