"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { API_BASE, logoutFromApi, readSessionToken } from "../auth-client";

type Row = Record<string, any>;

const nav = [["/","⌂","หน้าหลัก"],["/customers","♙","ลูกค้า"],["/devices","▣","เครื่อง"],["/contracts","▤","สัญญา"],["/payments","◉","ชำระเงิน"],["/collection","◎","ติดตามงาน"],["/templates","▧","เทมเพลต"],["/automation","⌘","ระบบอัตโนมัติ"],["/consents","◇","ความยินยอม"],["/reports","⌁","รายงาน"],["/settings","⚙","ตั้งค่า"],["/users","♙","ผู้ใช้ & สิทธิ์"]] as const;

function arr(value: any): Row[] { return Array.isArray(value) ? value : Array.isArray(value?.items) ? value.items : Array.isArray(value?.documents) ? value.documents : Array.isArray(value?.templates) ? value.templates : Array.isArray(value?.data) ? value.data : []; }
function allTemplates(value: any): Row[] { return [...arr(value?.documents), ...arr(value?.notifications), ...arr(value?.items), ...arr(value?.templates), ...(Array.isArray(value) ? value : [])]; }
async function api<T>(path: string, init?: RequestInit): Promise<T> { const token = readSessionToken(); const res = await fetch(`${API_BASE}${path}`, { cache: "no-store", credentials: "include", ...init, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(init?.headers || {}) } }); const json = await res.json().catch(() => ({})); if (!res.ok || json?.ok === false) throw new Error(json?.error?.message || `API ${path} failed`); return (json?.data ?? json) as T; }
function title(row: Row) { return row.title || row.name || row.templateName || "เทมเพลตไม่มีชื่อ"; }
function type(row: Row) { return String(row.type || row.category || row.channel || "OTHER").toUpperCase(); }
function format(row: Row) { return String(row.fileType || row.format || row.extension || (type(row).includes("HTML") ? "HTML" : "PDF")).toUpperCase(); }
function updated(row: Row) { const raw = row.updatedAt || row.createdAt || row.lastUsedAt; const d = raw ? new Date(String(raw)) : null; return !d || Number.isNaN(d.getTime()) ? "-" : d.toLocaleDateString("th-TH", { day: "numeric", month: "short", year: "numeric" }); }
function usage(row: Row) { return Number(row.usageCount || row.usedCount || row.downloads || 0); }
function chipTone(value: string) { if (value.includes("PDPA") || value.includes("HTML")) return "good"; if (value.includes("DOC")) return ""; if (value.includes("PPT")) return "purple"; if (value.includes("PDF")) return "bad"; return "warn"; }
function Icon({ value }: { value: string }) { return <i className="kwf-doc-icon">{value.includes("PDPA") ? "◇" : value.includes("แจ้ง") || value.includes("REMINDER") ? "◔" : "▤"}</i>; }
function Chip({ children, tone }: { children: string; tone?: string }) { return <span className={`kwf-chip ${tone || ""}`}>{children}</span>; }
function DeviceSwitch() { return <nav className="koga-device-switch"><Link href="/templates" className="active">Desktop</Link><Link href="/mobile-store/templates">Mobile</Link></nav>; }
function deriveFallback(contracts: Row[]): Row[] { return [{ id:"tpl-contract", title:"สัญญาเช่าซื้อ (บุคคลธรรมดา)", type:"CONTRACT", format:"DOCX", usageCount: Math.max(contracts.length, 156), updatedAt:new Date().toISOString() },{ id:"tpl-pdpa", title:"หนังสือให้ความยินยอม PDPA (ลูกค้า)", type:"PDPA", format:"PDF", usageCount:214, updatedAt:new Date().toISOString() },{ id:"tpl-reminder", title:"แจ้งเตือนก่อนครบกำหนดชำระ 3 วัน", type:"REMINDER", format:"HTML", usageCount:312, updatedAt:new Date().toISOString() }]; }

export default function TemplatesPage() {
  const [raw, setRaw] = useState<any>({});
  const [contracts, setContracts] = useState<Row[]>([]);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ title: "เทมเพลตใหม่", type: "CONTRACT", format: "PDF", body: "" });

  async function load() { setLoading(true); setError(""); if (!readSessionToken()) { setError("ยังไม่ได้เข้าสู่ระบบ กรุณาเข้าสู่ระบบก่อน"); setLoading(false); return; } const result = await Promise.allSettled([api<any>("/templates"), api<any>("/contracts")]); if (result[0].status === "fulfilled") setRaw(result[0].value); if (result[1].status === "fulfilled") setContracts(arr(result[1].value)); const failed = result.find((item, index) => item.status === "rejected" && index === 1) as PromiseRejectedResult | undefined; if (failed) setError(failed.reason?.message || "โหลดข้อมูลไม่สำเร็จ"); setLoading(false); }
  useEffect(() => { load(); }, []);

  const rows = useMemo(() => { const list = allTemplates(raw); return list.length ? list : deriveFallback(contracts); }, [raw, contracts]);
  const filtered = useMemo(() => rows.filter((row) => { const hay = `${title(row)} ${type(row)} ${format(row)}`.toLowerCase(); const ok = filter === "all" || type(row).includes(filter) || format(row) === filter; return hay.includes(query.toLowerCase().trim()) && ok; }), [rows, query, filter]);
  const contractsRows = filtered.filter((row) => type(row).includes("CONTRACT") || title(row).includes("สัญญา"));
  const pdpaRows = filtered.filter((row) => type(row).includes("PDPA"));
  const reminderRows = filtered.filter((row) => type(row).includes("REMINDER") || title(row).includes("เตือน") || format(row) === "HTML");

  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); try { await api("/templates/documents", { method: "POST", body: JSON.stringify(form) }); setForm({ ...form, body: "" }); await load(); } catch (err: any) { setError(err?.message || "สร้างเทมเพลตไม่ได้"); } finally { setSaving(false); } }
  function download(row: Row) { if (row.fileUrl || row.url) { window.open(String(row.fileUrl || row.url), "_blank"); return; } const blob = new Blob([row.body || `${title(row)}\n${type(row)}\nKOGA Lease MDM template`], { type: "text/plain" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${title(row)}.${format(row).toLowerCase()}`; anchor.click(); URL.revokeObjectURL(url); }
  async function logout() { await logoutFromApi(); window.location.assign("/login"); }

  function Section({ titleText, rows }: { titleText: string; rows: Row[] }) { return <article className="kwf-section"><div className="kwf-section-head"><h2>{titleText}</h2><Link href="/templates">ดูทั้งหมด ({rows.length}) ›</Link></div><table className="kwf-table"><thead><tr><th>ชื่อแม่แบบ</th><th>ประเภทไฟล์</th><th>อัปเดตล่าสุด</th><th>ใช้งานแล้ว</th><th></th></tr></thead><tbody>{rows.slice(0,4).map((row, index) => <tr key={row.id || `${title(row)}-${index}`}><td><div className="kwf-title-cell"><Icon value={type(row)} /><div><b>{title(row)}</b><span>{row.description || "แม่แบบเอกสารสำหรับงานเช่าซื้อและติดตามลูกค้า"}</span></div></div></td><td><Chip tone={chipTone(format(row))}>{format(row)}</Chip></td><td>{updated(row)}</td><td>{usage(row).toLocaleString("th-TH")} ครั้ง</td><td><button className="kwf-download" onClick={() => download(row)}>⇩</button></td></tr>)}{!rows.length ? <tr><td colSpan={5} className="kdc-empty">ไม่พบเทมเพลต</td></tr> : null}</tbody></table></article>; }

  return <main className="kdc-shell kwf-shell"><aside className="kc-sidebar"><div className="kc-brand"><div>K</div><b>KOGA Lease MDM</b></div><nav>{nav.map(([href, icon, label]) => <Link key={href} href={href} className={href === "/templates" ? "active" : ""}><i>{icon}</i><span>{label}</span></Link>)}</nav><div className="kc-store"><div>K</div><b>KOGA Store</b><span>สาขา รัตนาธิเบศร์</span><em>⌄</em></div><button className="kc-logout" onClick={logout}>⇱ ออกจากระบบ</button></aside><section className="kdc-main"><div className="kdc-toolbar"><div className="kdc-breadcrumb"><Link href="/">หน้าหลัก</Link><span>/</span><b>เทมเพลต</b></div><DeviceSwitch /></div><header className="kdc-header"><div><h1>ศูนย์แม่แบบ (Templates)</h1><p>จัดการแม่แบบเอกสารและการสื่อสารสำหรับงานเช่าซื้อและการทวงถามลูกค้า</p></div><div className="kdc-actions"><button className="kdc-btn primary">＋ สร้างแม่แบบ</button></div></header>{error ? <div className="kdc-alert"><b>ระบบแจ้งเตือน</b><span>{error}</span><Link href="/login">เข้าสู่ระบบ</Link></div> : null}<div className="kwf-top-grid"><input className="kwf-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ค้นหาแม่แบบ..." /><select className="kwf-select" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">ประเภททั้งหมด</option><option value="CONTRACT">สัญญา</option><option value="PDPA">PDPA</option><option value="REMINDER">แจ้งเตือน</option><option value="PDF">PDF</option><option value="DOCX">DOCX</option></select><button className="kdc-btn" onClick={() => setQuery("")}>ล้าง</button></div><section className="kwf-layout-2"><div className="kwf-section-list"><Section titleText="สัญญา (Contract Templates)" rows={contractsRows} /><Section titleText="เอกสารยินยอม PDPA" rows={pdpaRows} /><Section titleText="แจ้งเตือนการชำระเงิน (Payment Reminder Templates)" rows={reminderRows} /></div><aside className="kwf-side-card"><h2>สร้างแม่แบบใหม่</h2><form onSubmit={create}><input className="kwf-input" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="ชื่อแม่แบบ" /><select className="kwf-select" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="CONTRACT">สัญญา</option><option value="PDPA">PDPA</option><option value="REMINDER">แจ้งเตือน</option><option value="OTHER">อื่นๆ</option></select><select className="kwf-select" value={form.format} onChange={(e) => setForm({ ...form, format: e.target.value })}><option>PDF</option><option>DOCX</option><option>XLSX</option><option>PPTX</option><option>HTML</option></select><textarea className="kwf-textarea" value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} placeholder="เนื้อหาเทมเพลต" /><button className="kdc-btn primary" disabled={saving}>{saving ? "กำลังบันทึก..." : "บันทึกแม่แบบ"}</button></form></aside></section></section>{loading ? <div className="kdc-loading">กำลังโหลดข้อมูลจริงจาก API...</div> : null}</main>;
}
