"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { API_BASE, logoutFromApi, readSessionToken } from "../../auth-client";

type Row=Record<string,any>;
const menu=[{href:"/mobile-store",label:"หน้าหลัก",icon:"⌂"},{href:"/mobile-store/customers",label:"ลูกค้า",icon:"♙"},{href:"/mobile-store/devices",label:"คลังเครื่อง",icon:"▣"},{href:"/mobile-store/contracts",label:"สัญญา",icon:"▤"},{href:"/payments",label:"ชำระเงิน",icon:"฿"},{href:"/collection",label:"ติดตามงวด",icon:"◎"},{href:"/reports",label:"รายงาน",icon:"▥"},{href:"/settings",label:"ตั้งค่า",icon:"⚙"}];
function arr(v:any):Row[]{return Array.isArray(v)?v:Array.isArray(v?.items)?v.items:Array.isArray(v?.contracts)?v.contracts:Array.isArray(v?.data)?v.data:[]}
async function api<T>(path:string):Promise<T>{const token=readSessionToken();const res=await fetch(`${API_BASE}${path}`,{cache:"no-store",credentials:"include",headers:token?{Authorization:`Bearer ${token}`}:{}});const json=await res.json().catch(()=>({}));if(!res.ok||json?.ok===false)throw new Error(json?.error?.message||`API ${path} failed`);return (json?.data??json) as T}
function no(c:Row){return c.contractNo||c.code||c.id||"-"}function customer(c:Row){return c.customer?.fullName||c.customerName||c.customer?.name||c.customerId||"ไม่ระบุลูกค้า"}function device(c:Row){return c.device?.name||c.deviceName||[c.device?.brand,c.device?.model].filter(Boolean).join(" ")||c.deviceId||"ไม่ระบุเครื่อง"}function total(c:Row){return Number(c.totalAmount||c.amount||c.price||0)}function paid(c:Row){const items=Array.isArray(c.installments)?c.installments:[];return Number(c.paidInstallments||items.filter((i:Row)=>["PAID","CONFIRMED"].includes(String(i.status||"").toUpperCase())).length||0)}function months(c:Row){return Number(c.totalInstallments||c.months||c.termMonths||12)}function pct(c:Row){return Math.min(100,Math.round((paid(c)/Math.max(months(c),1))*100))}function status(c:Row){const raw=String(c.status||"").toUpperCase();if(raw.includes("OVER"))return {label:"ค้างชำระ",tone:"bad",tab:"overdue"};if(raw.includes("CLOSE")||raw.includes("DONE"))return {label:"ปิดแล้ว",tone:"info",tab:"closed"};return {label:"ใช้งานอยู่",tone:"good",tab:"active"}}function date(c:Row,key="startDate"){const v=c[key]||c.createdAt;const d=v?new Date(String(v)):null;return !d||Number.isNaN(d.getTime())?"-":d.toLocaleDateString("th-TH",{day:"2-digit",month:"short",year:"numeric"})}function money(n:number){return `฿${n.toLocaleString("th-TH",{maximumFractionDigits:0})}`}function Chip({children,tone}:{children:string;tone:string}){return <span className={`kdc-chip ${tone}`}>{children}</span>}function DeviceSwitch(){return <nav className="koga-device-switch ms-device-switch"><Link href="/contracts">Desktop</Link><Link href="/mobile-store/contracts" className="active">Mobile</Link></nav>}
export default function ContractsMobileReal(){const [contracts,setContracts]=useState<Row[]>([]);const [query,setQuery]=useState("");const [tab,setTab]=useState("all");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [menuOpen,setMenuOpen]=useState(false);async function load(){setLoading(true);setError("");if(!readSessionToken()){setError("ยังไม่ได้เข้าสู่ระบบ กรุณาเข้าสู่ระบบก่อน");setLoading(false);return}try{setContracts(arr(await api<any>("/contracts")))}catch(e:any){setError(e?.message||"โหลดสัญญาไม่สำเร็จ")}finally{setLoading(false)}}useEffect(()=>{load()},[]);const filtered=useMemo(()=>contracts.filter(c=>{const hay=`${no(c)} ${customer(c)} ${device(c)}`.toLowerCase();const s=status(c);return hay.includes(query.toLowerCase().trim())&&(tab==="all"||s.tab===tab)}),[contracts,query,tab]);async function logout(){await logoutFromApi();window.location.assign("/login")}
return <main className="kdc-mobile">{menuOpen?<button className="ms-backdrop" aria-label="ปิดเมนู" onClick={()=>setMenuOpen(false)}/>:null}<aside className={`ms-drawer ${menuOpen?"open":""}`}><div className="ms-drawer-head"><div className="ms-logo">K</div><div><b>KOGA Lease MDM</b><span>Mobile Store</span></div><button onClick={()=>setMenuOpen(false)}>×</button></div><DeviceSwitch/><nav>{menu.map(item=><Link key={item.href} href={item.href} className={item.href==="/mobile-store/contracts"?"active":""} onClick={()=>setMenuOpen(false)}><i>{item.icon}</i><span>{item.label}</span></Link>)}</nav><div className="ms-drawer-status"><b>{error?"API error":"API live"}</b><span>{API_BASE}</span></div><button className="ms-logout" onClick={logout}>ออกจากระบบ</button></aside><header className="kdc-mobile-top"><button onClick={()=>setMenuOpen(true)}>☰</button><h1><span>KOGA</span> Lease MDM</h1><button onClick={load}>↻</button></header><DeviceSwitch/><section className="kdc-mobile-title"><h2>สัญญา</h2><button onClick={()=>setTab(tab==="all"?"overdue":"all")}>▽ ตัวกรอง</button></section><div className="kdc-mobile-tabs"><button className={tab==="all"?"active":""} onClick={()=>setTab("all")}>ทั้งหมด</button><button className={tab==="active"?"active":""} onClick={()=>setTab("active")}>ใช้งานอยู่</button><button className={tab==="closed"?"active":""} onClick={()=>setTab("closed")}>ปิดแล้ว</button></div><label className="kdc-mobile-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาสัญญา ลูกค้า หรือเครื่อง"/></label>{error?<section className="ms-error"><b>ระบบยังไม่พร้อม</b><span>{error}</span><Link href="/login">เข้าสู่ระบบ</Link></section>:null}<section className="kdc-mobile-list">{filtered.map(c=><article key={c.id||no(c)} className="kdc-mobile-card kdc-mobile-contract"><div className="kdc-mobile-row" style={{justifyContent:"space-between"}}><h3>{no(c)}</h3><Chip tone={status(c).tone}>{status(c).label}</Chip></div><div className="kdc-mobile-row">♙ <b>{customer(c)}</b></div><div className="kdc-mobile-row">▯ <span>{device(c)}</span></div><div className="kdc-mobile-row">▤ <span>เริ่มสัญญา {date(c)} | สิ้นสุดสัญญา {date(c,"endDate")}</span></div><div className="kdc-mobile-progress-label"><span>ชำระแล้ว {pct(c)}%</span><span>งวดที่ {paid(c)} / {months(c)}</span></div><div className="kdc-progress"><i style={{width:`${pct(c)}%`,background:status(c).tone==="bad"?"#ef4444":undefined}}/></div><div className="kdc-mobile-amount"><span>ยอดรวมสัญญา</span><strong>{money(total(c))}</strong></div></article>)}{!filtered.length?<div className="kdc-empty">ไม่พบสัญญาที่ตรงกับเงื่อนไข</div>:null}</section>{loading?<div className="kdc-loading">กำลังโหลดข้อมูลจริงจาก API...</div>:null}</main>}
