"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { API_BASE, logoutFromApi, readSessionToken } from "../../auth-client";

type Row = Record<string, any>;
const menu=[{href:"/mobile-store",label:"หน้าหลัก",icon:"⌂"},{href:"/mobile-store/customers",label:"ลูกค้า",icon:"♙"},{href:"/mobile-store/devices",label:"คลังเครื่อง",icon:"▣"},{href:"/mobile-store/contracts",label:"สัญญา",icon:"▤"},{href:"/payments",label:"ชำระเงิน",icon:"฿"},{href:"/collection",label:"ติดตามงวด",icon:"◎"},{href:"/reports",label:"รายงาน",icon:"▥"},{href:"/settings",label:"ตั้งค่า",icon:"⚙"}];
function arr(v:any):Row[]{return Array.isArray(v)?v:Array.isArray(v?.items)?v.items:Array.isArray(v?.devices)?v.devices:Array.isArray(v?.data)?v.data:[]}
async function api<T>(path:string):Promise<T>{const token=readSessionToken();const res=await fetch(`${API_BASE}${path}`,{cache:"no-store",credentials:"include",headers:token?{Authorization:`Bearer ${token}`}:{}});const json=await res.json().catch(()=>({}));if(!res.ok||json?.ok===false)throw new Error(json?.error?.message||`API ${path} failed`);return (json?.data??json) as T}
function deviceName(d:Row){return d.name||d.deviceName||[d.brand,d.model].filter(Boolean).join(" ")||"ไม่ระบุเครื่อง"}function sub(d:Row){return [d.storage,d.color,d.variant].filter(Boolean).join(" • ")||d.description||"-"}function imei(d:Row){return d.imei||d.IMEI||d.serial||d.serialNumber||"-"}function loc(d:Row){return d.location||d.branch||d.storeName||"คลังสินค้า"}function control(d:Row){const raw=String(d.controlStatus||d.mdmStatus||d.enrollmentStatus||"").toUpperCase();if(raw.includes("NOT")||raw.includes("OFF")||raw.includes("UN"))return {label:"ออฟไลน์",tone:"warn"};return {label:"ออนไลน์",tone:"good"}}function payment(d:Row){const raw=String(d.paymentStatus||d.leaseStatus||d.status||"").toUpperCase();if(raw.includes("OVER")||raw.includes("DUE"))return {label:"ค้าง 1 งวด",tone:"warn"};return {label:"ปกติ",tone:"good"}}function Chip({children,tone}:{children:string;tone:string}){return <span className={`kdc-chip ${tone}`}>{children}</span>}
function DeviceSwitch(){return <nav className="koga-device-switch ms-device-switch"><Link href="/devices">Desktop</Link><Link href="/mobile-store/devices" className="active">Mobile</Link></nav>}
export default function DeviceMobileReal(){const [devices,setDevices]=useState<Row[]>([]);const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [menuOpen,setMenuOpen]=useState(false);async function load(){setLoading(true);setError("");if(!readSessionToken()){setError("ยังไม่ได้เข้าสู่ระบบ กรุณาเข้าสู่ระบบก่อน");setLoading(false);return}try{setDevices(arr(await api<any>("/devices")))}catch(e:any){setError(e?.message||"โหลดข้อมูลเครื่องไม่สำเร็จ")}finally{setLoading(false)}}useEffect(()=>{load()},[]);const filtered=useMemo(()=>devices.filter(d=>{const hay=`${deviceName(d)} ${sub(d)} ${imei(d)} ${loc(d)}`.toLowerCase();const c=control(d).tone;return hay.includes(query.toLowerCase().trim())&&(filter==="all"||filter===c)}),[devices,query,filter]);async function logout(){await logoutFromApi();window.location.assign("/login")}
return <main className="kdc-mobile">{menuOpen?<button className="ms-backdrop" aria-label="ปิดเมนู" onClick={()=>setMenuOpen(false)}/>:null}<aside className={`ms-drawer ${menuOpen?"open":""}`}><div className="ms-drawer-head"><div className="ms-logo">K</div><div><b>KOGA Lease MDM</b><span>Mobile Store</span></div><button onClick={()=>setMenuOpen(false)}>×</button></div><DeviceSwitch/><nav>{menu.map(item=><Link key={item.href} href={item.href} className={item.href==="/mobile-store/devices"?"active":""} onClick={()=>setMenuOpen(false)}><i>{item.icon}</i><span>{item.label}</span></Link>)}</nav><div className="ms-drawer-status"><b>{error?"API error":"API live"}</b><span>{API_BASE}</span></div><button className="ms-logout" onClick={logout}>ออกจากระบบ</button></aside><header className="kdc-mobile-top"><button onClick={()=>setMenuOpen(true)}>☰</button><h1><span>KOGA</span> Lease MDM</h1><button onClick={load}>↻</button></header><DeviceSwitch/><section className="kdc-mobile-title"><h2>คลังอุปกรณ์</h2><button onClick={()=>setFilter(filter==="all"?"warn":"all")}>▽ ตัวกรอง</button></section><label className="kdc-mobile-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาอุปกรณ์, IMEI, รุ่น"/></label>{error?<section className="ms-error"><b>ระบบยังไม่พร้อม</b><span>{error}</span><Link href="/login">เข้าสู่ระบบ</Link></section>:null}<section className="kdc-mobile-list">{filtered.map(d=><article key={d.id||imei(d)} className="kdc-mobile-card kdc-mobile-device"><div className="kdc-thumb"/><div><h3>{deviceName(d)}</h3><p>IMEI: {imei(d)}</p><p>สถานที่: {loc(d)}</p></div><div className="kdc-mobile-status"><span>สถานะควบคุม</span><Chip tone={control(d).tone}>{control(d).label}</Chip><span>สถานะผ่อนชำระ</span><Chip tone={payment(d).tone}>{payment(d).label}</Chip></div></article>)}{!filtered.length?<div className="kdc-empty">ไม่พบอุปกรณ์ที่ตรงกับเงื่อนไข</div>:null}</section>{loading?<div className="kdc-loading">กำลังโหลดข้อมูลจริงจาก API...</div>:null}</main>}
